## 捕获错误

### try-catch

把可能抛出错误的代码放在 try 块中，当错误发生时会立刻停止代码执行进入 catch 块。

传入 catch 中的错误对象包含的兼容属性只有 `message`。

```js
try {
    // code here
} catch (error) {
    alert(error.message);
}
```

### finally

就算 try 或 catch 块中包含 return 语句也会执行的子句。

## 抛出错误

### throw

与 try-catch 语句相配的还有一个 throw 操作符，用于随时抛出自定义错误。抛出错误时，必须要给 throw 操作符指定一个值，这个值是什么类型，没有要求。下列代码都是有效的。

```js
throw 12345;
throw "Hello world!";
throw true;
throw { name: "JavaScript"};
```

在遇到 throw 操作符时，代码会立即停止执行。仅当有 try-catch 语句捕获到被抛出的值时，代码才会继续执行。

通过使用某种内置错误类型，可以更真实地模拟浏览器错误。每种错误类型的构造函数接收一个参数，即实际的错误消息：

```js
throw new Error("Something bad happened.");
throw new TypeError("What type of variable do you take me for?");
throw new ReferenceError("You didn’t cite your references properly.");
throw new SyntaxError("I don’t like your syntax.");
throw new RangeError("Sorry, you just don’t have the range.");
throw new EvalError("That doesn’t evaluate.");
throw new URIError("Uri, is that you?");
```

## 自定义错误类型

利用原型链还可以通过继承 Error 来创建自定义错误类型（原型链在第 6 章中介绍） 。此时，需要为新创建的错误类型指定 name 和 message 属性。

```js
function CustomError(message){
    this.name = "CustomError";
    this.message = message;
}
CustomError.prototype = new Error();
throw new CustomError("My message");
```

浏览器对待继承自 Error 的自定义错误类型，就像对待其他错误类型一样。如果要捕获自己抛出的错误并且把它与浏览器错误区别对待的话，创建自定义错误是很有用的。

## 将错误记录到服务器

```js
function logError(sev, msg){
    var img = new Image();
    img.src = "log.php?sev=" + encodeURIComponent(sev) + "&msg=" +
    encodeURIComponent(msg);
}
```

## 时机

到抛出错误与捕获错误，我们认为只应该捕获那些你确切地知道该如何处理的错误。捕获错误的目的在于避免浏览器以默认方式处理它们；而抛出错误的目的在于提供错误发生具体原因的消息。
